logging:
  level:
    root: INFO
  pattern:
    console: 

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb

  output:
    ansi:
      enabled:  ALWAYS