logging:
  level:
    root: INFO

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./src/main/resources/data
  liquibase:
    enabled: true
    change-log: classpath:liquibase-outputChangeLog.xml

  output:
    ansi:
      enabled:  ALWAYS